[phases.setup]
nixPkgs = ['python310', 'ffmpeg', 'libopus', 'pkg-config']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'python gateway_bot.py'
